### ISSUE TITLE
Click doesn't appear to be working...

### ISSUE THREAD

**Issue by JStorey42** [rundel/hayalbaz#3]
Thanks for this package!

I'm having some trouble using the click() function. I tried it on a few sites, and always ran into this error:

Error: Chromote: timed out waiting for response to command Runtime.evaluate

Am I missing something? Thanks for any help!

**Comment by rundel** [comment]
Do you have the viewer open (`$view()` method) this seems to cause some kind of weird issue with the click method. Usually if you close the viewer things work correctly. This makes debugging a pain I know but I think the underlying issue is with chromote but I haven't had much luck tracking it down.

I originally reported this in rstudio/chromote#30.

**Comment by JStorey42** [comment]
I did! I closed it and it worked perfectly! 

Thanks for your super fast help! Really been enjoying using this package (especially after using raw chromote and Selenium)!

Thanks again!

**Comment by rundel** [comment]
Glad you are finding it useful - i had similar pain points which is why i started putting this together.
